import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Website Doctor",
  description:
    "Analyze websites and uncover UX, SEO, accessibility, and design improvements.",
>>>>>>> 80365d441e2c6bed578a07aa31c847d067e6b3bd
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
>>>>>>> 80365d441e2c6bed578a07aa31c847d067e6b3bd
        {children}
      </body>
    </html>
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> 80365d441e2c6bed578a07aa31c847d067e6b3bd
